### ISSUE TITLE
Неправильне кодування

### ISSUE THREAD

**Issue by YaroslavP32** [YaroslavP32/articles#1]
Змінити кодування з ANSI на UTF-8

**Comment by volodymyr-kushnir** [comment]
@YaroslavP32 то як, замінив? Якщо замінив, то чому ця проблема не закрита, без **Label** і без **Assignee**?

_P. S. А спробуй ще, будь ласка, щось з [**лайфхаків**](https://github.com/volodymyr-kushnir/agenda) впровадити, маркдаун, наприклад. Або може **README.md** з коротким описом репозиторію._
